[tool.poetry]
name = "articuno-3"
version = "0.1.0"
description = ""
authors = ["JimmyBlue <<>>"]

[tool.poetry.dependencies]
python = "^3.8.12"
discord-py-interactions = "4.1.0"
python-dotenv = "0.19.2"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
